server:
  port: 80

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ecjtu.exam.pojo

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/smart_exam?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  http:
    encoding:
      charset: UTF-8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 5
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000
jwt:
  config:
    key: yjfyjf
    ttl: 3600000

#七牛云配置
qiniuyun:
  config:
    accessKey: gyv_jtbDRW3o0nMAYmbu1acgAnPxfDM2JEvx4Qq4
    secretKey: 3M51U7lThWPzYEf9ZW0feITgwcRp7kxthOKL8qKz
    bucket: ecjtu-bishe
    baseUrl: http://q6r3ukk9c.bkt.clouddn.com/

